### ISSUE TITLE
Interactive Trigonometry

### ISSUE THREAD

**Issue by heerdyes** [dynamic-learning/simulation-library-ideas#7]
Interactive visualizations for trigonometry (and possibly trigonometry art).
Initial sketch: [https://editor.p5js.org/heerdyes/sketches/Z5jBpu-FS](https://editor.p5js.org/heerdyes/sketches/Z5jBpu-FS)

**Comment by heerdyes** [comment]
Do you have a separate repo for committing the sketches?

**Comment by JithinKS97** [comment]
Wow, this looks cool. If I understand correctly, this helps us to compare the values of sin, cos and tan functions dynamically? I think the graph is a bit small to see. Would it make sense to make it a little bigger and maybe we could also show the actual values of the functions? Just suggestions.

If you think we are ready, I can add it to the Dynamic Learning app.

**Comment by JithinKS97** [comment]
Also, what are the concepts that you think students can learn from this visualization?

**Comment by JithinKS97** [comment]
We don't have a repo for storing the sketches. The problem that I see with storing the sketches in the repo is that, if we do some change to the sim in the web editor, we have to make a change in the repo also right to make it consistent? So I think its better if we just keep the sketch in web editor itself.

**Comment by heerdyes** [comment]
> Wow, this looks cool. If I understand correctly, this helps us to compare the values of sin, cos and tan functions dynamically? I think the graph is a bit small to see. Would it make sense to make it a little bigger and maybe we could also show the actual values of the functions? Just suggestions.
> 
> If you think we are ready, I can add it to the Dynamic Learning app.

Oh yes I can make it bigger. Will add counters for the current values of sine, cosine and tangent too. I was exploring the idea of a live meter that shows functions varying with time visually.

**Comment by heerdyes** [comment]
> Also, what are the concepts that you think students can learn from this visualization?

- periodicity seems to be a central theme with trigonometry. i was also thinking of having a motor on/off button that automated the rotation of point C. the point keeps circling causing the scope to generate the instantly recognizable wave forms of sine and cosine.
- tangent going off to infinity is another important concept. now it just shows out of bounds when theta reaches 90 and 270; after i add the counter the actual values will be seen.

**Comment by JithinKS97** [comment]
OK, once you are satisfied with the simulation, we can add it to dynamic learning. I wonder if you have any plans to use these simulations and teach. If you have any plans like that. I'm ready to chime in and discuss and even join you in creating visualizations.

**Comment by heerdyes** [comment]
Well I currently teach creative programming and contemporary music to kids (mostly python and processing). It has been mostly an independent initiative although I have just recently started reaching out to schools who might be interested with any sort of creative programming projects/workshops. I'm especially interested in Sonic Pi and Processing. My courses look like this: [https://heerdyes.wordpress.com/learn/](https://heerdyes.wordpress.com/learn/)
I find the creative computing (and DIY) approach to be beneficial in teaching almost any subject. This kind of thing however does seem under explored around here (Bengaluru)!

**Comment by heerdyes** [comment]
I haven't actually taught math or science for that matter! Only programming and music.

**Comment by JithinKS97** [comment]
Ok, I hope simulations that we create here will become useful in your courses and projects and also others using our platform.

We also have a repository where we are trying to create a collection of libraries that might come in handy during the development of interactive visualizations. Do check that also.

**Comment by heerdyes** [comment]
> Ok, I hope simulations that we create here will become useful in your courses and projects and also others using our platform.
> 
> We also have a repository where we are trying to create a collection of libraries that might come in handy during the development of interactive visualizations. Do check that also.

Cool!

**Comment by heerdyes** [comment]
Updated the [sketch](https://editor.p5js.org/heerdyes/sketches/Z5jBpu-FS).
Values per function are being displayed. Size is now bigger. Displaying angle as degrees for convenience.

**Comment by JithinKS97** [comment]
Thanks. I've added the simulation to Dynamic Learning.
Take a look here
https://www.dynamiclearning.io/workbook/5fcc4e5737ff71001795fb0b
https://www.dynamiclearning.io/simulations

Also, I think it would be nicer if you can add the automatic angle incrementer. Because now when the user changes the graph, it looks jagged. 

Also is there any way in which you could have used lines to connect the points instead of the dots in the graph? I'm just thinking of ways to improve the visualization

**Comment by heerdyes** [comment]
> Thanks. I've added the simulation to Dynamic Learning.
> Take a look here
> https://www.dynamiclearning.io/workbook/5fcc4e5737ff71001795fb0b
> https://www.dynamiclearning.io/simulations
> 
> Also, I think it would be nicer if you can add the automatic angle incrementer. Because now when the user changes the graph, it looks jagged.
> 
> Also is there any way in which you could have used lines to connect the points instead of the dots in the graph? I'm just thinking of ways to improve the visualization

Cool! Yeah the auto rotation would make the waveforms really obvious. Let me try and add that.
About joining the points for continuity do you suggest using simple lines? or some sort of extrapolation using math?

**Comment by heerdyes** [comment]
Updated [sketch](https://editor.p5js.org/heerdyes/sketches/Z5jBpu-FS).
Added a start/stop button to control automatic rotation the circle. For now the rotation speed is constant.

**Comment by JithinKS97** [comment]
Wow, I just tried it and this the graph generated is really beautiful to see . Thanks for this.

**Comment by JithinKS97** [comment]
A small additional feature that might truly benefit will be the ability to pause at some moment of time. I think this feature can be used by teachers to explain to the students the behavior of the functions at different instants, like different quadrants.

**Comment by heerdyes** [comment]
> Wow, I just tried it and this the graph generated is really beautiful to see . Thanks for this.

Thanks!

> A small additional feature that might truly benefit will be the ability to pause at some moment of time. I think this feature can be used by teachers to explain to the students the behavior of the functions at different instants, like different quadrants.

do you mean pausing the oscilloscope from plotting?

**Comment by JithinKS97** [comment]
Yes maybe use noLoop() function on the click of a button? And loop() to
continue?

**Comment by heerdyes** [comment]
yeah i can do that. basically i have to stop time (t) and the oscilloscope will freeze at the current state.

**Comment by JithinKS97** [comment]
The use case is this. Suppose I have to tell my students the sign of the
functions at the 3rd quadrant. So when it reaches 3rd quadrant, I will
pause the rotation and will describe that to students. Do you think that'll
help?

**Comment by heerdyes** [comment]
ah ok. let me see if i can add an on/off switch for the scope.

**Comment by heerdyes** [comment]
Updated [sketch](https://editor.p5js.org/heerdyes/sketches/Z5jBpu-FS). I have linked the start/stop button to also control the oscilloscope signal. When the rotation stops the graph drawing also stops. Hmm maybe I should make the behavior of the oscilloscope configurable. I guess eventually I will end up building a library of reusable components!

**Comment by JithinKS97** [comment]
Yeah, that's right. I think this visualization can be used to explain a good number of concepts in trigonometry.

**Comment by heerdyes** [comment]
> Yeah, that's right. I think this visualization can be used to explain a good number of concepts in trigonometry.

cool! this area is rather under-utilized in education. i feel a lot of subjects could be better explained with creative simulations.
